apiVersion: v1
kind: Deployment
metadata:
  name: nginx-demo
  labels:
    component: nginx
spec: 
  replicas: 3
  selector:
    matchLabels:
      component: nginx
  template:
    metadata:
      labels:
       component: nginx
    spec:
      containers:
      - name: nginx
      image: nginx:1.22
